### ISSUE TITLE
[ERROR] begin_create_operation failed, when executing sync

### ISSUE THREAD

**Issue by kaz-tk** [cloudforet-io/plugin-azure-cost-mgmt-cost-datasource#48]
now we are trying to use this plugin, but below error happens.
will dive into details

```python
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/pygrpc/api.py", line 100, in _generate_response
    for response in response_iterator:
  File "/usr/local/lib/python3.8/site-packages/plugin_azure_cost_mgmt_cost_datasource-1.1.9-py3.8.egg/cloudforet/cost_analysis/interface/grpc/plugin/cost.py", line 15, in get_data
    for costs_data in response_stream:
  File "/usr/local/lib/python3.8/site-packages/plugin_azure_cost_mgmt_cost_datasource-1.1.9-py3.8.egg/cloudforet/cost_analysis/manager/cost_manager.py", line 51, in get_data
    blobs = self.azure_cm_connector.begin_create_operation(
  File "/usr/local/lib/python3.8/site-packages/plugin_azure_cost_mgmt_cost_datasource-1.1.9-py3.8.egg/cloudforet/cost_analysis/connector/azure_cost_mgmt_connector.py", line 108, in begin_create_operation
    raise ERROR_UNKNOWN(message=f'[ERROR] begin_create_operation failed')
spaceone.core.error.ERROR_UNKNOWN:
        error_code = ERROR_UNKNOWN
        status_code = INTERNAL
        message = [ERROR] begin_create_operation failed
2024-02-08T09:22:27.265Z [ERROR]       (azure_cost_mgmt_connector.py:107) [begin_create_operation] error message: Operation returned an invalid status 'Not Acceptable'
2024-02-08T09:22:27.266Z [ERROR]       (api.py:93) (Error) => [ERROR] begin_create_operation failed
        error_code = ERROR_UNKNOWN
        status_code = INTERNAL
        message = [ERROR] begin_create_operation failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/plugin_azure_cost_mgmt_cost_datasource-1.1.9-py3.8.egg/cloudforet/cost_analysis/connector/azure_cost_mgmt_connector.py", line 94, in begin_create_operation
    response = self.cost_mgmt_client.generate_cost_details_report.begin_create_operation(scope=scope,
  File "/usr/local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/mgmt/costmanagement/operations/_generate_cost_details_report_operations.py", line 329, in begin_create_operation
    raw_result = self._create_operation_initial(
  File "/usr/local/lib/python3.8/site-packages/azure/mgmt/costmanagement/operations/_generate_cost_details_report_operations.py", line 164, in _create_operation_initial
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Not Acceptable'
```

**Comment by ImMin5** [comment]
Hi, @kaz-tk 

I apologize for the delayed response. After reviewing the details you provided, it seems that there might be a network issue or an issue with your billing account status.Of course, I will conduct further investigation. Could you please check your environment and the status of your Azure Billing Account as well?
